name: Mirror Repository to SIM

on:
  workflow_call:
    inputs:
      source_repository:
        description: 'Source repository name'
        required: false
        type: string
        default: 'unknown'
      target_repository:
        description: 'Target repository name'
        required: false
        type: string
        default: 'unknown'
    secrets:
      GITHUB_TOKEN:
        description: 'GitHub token for accessing repositories'
        required: false

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: Hello World Job
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Say Hello
        run: |
          echo "🎉 Hello World from ${{ github.repository }}!"
          echo "📅 Current date: $(date)"
          echo "🌿 Branch: ${{ github.ref_name }}"
          echo "📝 Commit: ${{ github.sha }}"
          echo "👤 Triggered by: ${{ github.actor }}"

      - name: Repository Information
        run: |
          echo "Repository Details:"
          echo "  Name: ${{ github.repository }}"
          echo "  Owner: ${{ github.repository_owner }}"
          echo "  Event: ${{ github.event_name }}"
          echo "  Workflow: ${{ github.workflow }}"
          echo "  Run ID: ${{ github.run_id }}"
          echo "  Run Number: ${{ github.run_number }}"
          echo "  Source Repository: ${{ inputs.source_repository }}"
          echo "  Target Repository: ${{ inputs.target_repository }}"

      - name: Environment Test
        run: |
          echo "Environment Information:"
          echo "  OS: ${{ runner.os }}"
          echo "  Architecture: ${{ runner.arch }}"
          echo "  Working Directory: $(pwd)"
          echo "  Files in directory:"
          ls -la

      - name: Success Message
        run: |
          echo "✅ Hello World workflow completed successfully!"
          echo "This workflow was automatically added by the InfraOps webhook service."
          echo "Mirroring from: ${{ inputs.source_repository || 'unknown' }}"
          echo "Mirroring to: ${{ inputs.target_repository || 'unknown' }}"
